### ISSUE TITLE
onboard in vertice the mail is not sent

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/libgo#58]
UnexpectedResponseError URL=https://api.mailgun.net/v2/ojamail.megambox.com/messages ExpectedOneOf=[]int{200, 202, 204} Got=400

**Comment by indykish** [comment]
@ranjithamca  The domain `megambox.com` has expired. Trying to buy it back.

**Comment by indykish** [comment]
@rajthilakmca  The domain `megambox.com` is renewed in godaddy. This should work now. Hence closing this problem.
